version: 2
jobs:
  build_node6:
    docker:
      - image: circleci/node:6.10

    working_directory: ~/capnp-stream

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-v6-{{ checksum "package.json" }}
          - v1-dependencies-v6-
          - v1-dependencies-

      - run:
          name: Install capnp
          command: |
            curl -O https://capnproto.org/capnproto-c++-0.6.1.tar.gz
            tar zxf capnproto-c++-0.6.1.tar.gz
            cd capnproto-c++-0.6.1
            ./configure
            make -j6 check
            sudo make install

      - run:
          name: configure NPM registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

      - run:
          name: install dependencies
          command: npm install --no-optional

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-v6-{{ checksum "package.json" }}

      - run:
          name: unit tests
          command: npm test

      - run:
          name: coverage reporting
          command: npm run coverage:submit

  build_node8:
    docker:
      - image: circleci/node:8.10


    working_directory: ~/capnp-stream

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-v8-{{ checksum "package.json" }}
          - v1-dependencies-v8-
          - v1-dependencies-

      - run:
          name: Install capnp
          command: |
            curl -O https://capnproto.org/capnproto-c++-0.6.1.tar.gz
            tar zxf capnproto-c++-0.6.1.tar.gz
            cd capnproto-c++-0.6.1
            ./configure
            make -j6 check
            sudo make install

      - run:
          name: configure NPM registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

      - run:
          name: install dependencies
          command: npm install --no-optional

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-v8-{{ checksum "package.json" }}

      - run:
          name: unit tests
          command: npm test

      - run:
          name: coverage reporting
          command: npm run coverage:submit

  deploy:
    docker:
      - image: circleci/node:8.10

    steps:
        - attach_workspace:
            at: ~/

        - run:
            name: configure NPM registry
            command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

        - run:
            name: configure GitHub SSH
            command: mkdir -p ~/.ssh && ssh-keyscan -H github.com > ~/.ssh/known_hosts

        - run:
            working_directory: ~/capnp-stream
            name: publish
            command: |
                npm publish && npm run release:tag;

workflows:
  version: 2

  build_test_deploy:
    jobs:
        - build_node6
        - build_node8
        # we only deploy if build_node6 && build_node8 both succeed and if on master.
        - deploy:
            requires:
                - build_node6
                - build_node8
            filters:
                branches:
                    only: master
